name: workflow with Azure VM

on:

  push:
    branches:
      - main
      - 'feature/*'
  workflow_dispatch:

jobs: 
  build-push :
    name: Build & Push an image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup ssh and connect to Azure Vm
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_VM_PRIVATE_KEY }}
          port: 22
          script: |
            # Set variables
            IMAGE_NAME="my-app"
            IMAGE_TAG="latest"
            REGISTRY_URL="docker.io/${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME"
        
      
      - name: DockerHub Login
        uses: docker/login-action@v2.2.0
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD}}
      

       
   