name: Unit Test for Nginx Image

on:

    push:
      branches:
        - main
        - 'feature/*'
    workflow_dispatch:

jobs:
  unit-testing:
    name: Unit testing for Nginx
    runs-on: ubuntu:latest
    services:
        nginx:
          image: machanikrishnakumar/k-nginx:latest
          ports: 
            - 80:80
          options: --health-cmd="curl --fail http://localhost || exit 1" --health-interval=10s --health-timeout=5s --health-retries=3
